version: '1'
services:
  postgres:
    image: postgres:latest
    container_name: course-clients
    ports:
      - '5432:5432'
    volumes:
      - progresDB:/data/postgres
    env_file:
      - ./.env
volumes:
  progresDB: